### ISSUE TITLE
Chinese language bug

### ISSUE THREAD

**Issue by shenfan19** [scholer/TextToSpeech#1]
Hi, Thank you for your package, it is almost perfect in sublime, and really helpful for me to listen and organize txt folders in sublime.
However, there's the disappointing issue that in reading Chinese language, I mean in UTF-8 format, it is pronouncing completely wrong characters.
Could you please have a check if it is picking sentence and words in confused steps? As I know, the length of Chinese characters are always in double or 4 times long than English charactors.
If you do not know Chinese language, I can be the supporter if you need any information or support. Or you can advise me how to modify the script, as I don't have any experience in plugin coding.
I really like this package, thanks!

**Comment by shenfan19** [comment]
Hi, I found the reason, it is because when we transfer UTF8 code to TTS, the TTS consider it to be ANSI code.
I wish I could have a branche for manual install to read Chinese charactors, it could be add a function to generate UTF8 to ANSI before touch the TTS. Could you please help me to figure out where or how to do this in the code? Thanks!

**Comment by silence19** [comment]
I have partly fix the bug, it is becuase Chinese charactors are only shown in UTF-8 code in sublime.
Before calling the sentence.encode() method, it is already utf-8 in sentence variable. It is encoded again when use the encode(), wrong charactors are recoganized by SAPI.
To fix it, we could just remove the '.encode()'.
However, as I don't know the situation in other languages, I just forked a branche of this to my own space.

**Comment by shenfan19** [comment]
I have partly fix the bug, it is becuase Chinese charactors are only shown in UTF-8 code in sublime.
Before calling the sentence.encode() method, it is already utf-8 in sentence variable. It is encoded again when use the encode(), wrong charactors are recoganized by SAPI.
To fix it, we could just remove the '.encode()'.
However, as I don't know the situation in other languages, I just forked a branche of this to my own space.
