### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by LeaMariii** [scholer/TextToSpeech#3]
On Windows 10, all the spoken texts are interpreted with a different encoding (ISO 8859-1 probably). 

E.g. the German umlauts `ä`, `ö` and `ü` come out as `Ã¤`, `Ã¶` and `Ã¼`.

So if I let it read a text like "The grass is always gr***ü***ner on the other side." it literally reads:

"The grass is always gr***ã-one-quarter***ner on the other side."

This happens even if the file is saved with ISO 8859-1 encoding.

**Comment by shenfan19** [comment]
Hi michaelgrohn,
I happened to meet the issue, too. It's the encoding of Chinese.
Fortunately, I have solved this by just removing little code, and kept it in my own fork.
Would you like to have a try with that? Although I don't know if it works for your code.
You can find it at https://github.com/silence19/TextToSpeech/blob/master/simple_tts/tts_win.py, or you can see it in the pull requests here.
Thanks if you can share any comments!

**Comment by LeaMariii** [comment]
Works great, thx!
